Add files via upload
lightrun-platform/lightrun pull request #17
Opened 2023-02-01 07:21 UTC by JoeyLightrun

2023-02-01 07:23 UTC, JoeyLightrun commented
Improved examples

2023-02-02 20:39 UTC, mjsambol requested changes
Nicely done, just a few small change requests please

2023-02-02 20:39 UTC, mjsambol commented on examples/Java/README.md
> +Make sure to replace /path/to/agent/ with the proper path to your agent. This must be a relative path.
"relative" here should be "absolute" - any path that starts with / is an absolute path so your example contradicts your text ;)

2023-02-02 20:39 UTC, mjsambol commented on examples/Python/README.md
> +python sortArray.py -OR- python3 sortArray.py
it would be better to split this up onto separate rows, people copy and paste without checking carefully what they're copying

2023-02-02 20:39 UTC, mjsambol commented on examples/Python/sortArray.py
> +        import lightrun
I think that this import should be on line 3, together with the other imports. I see the value of keeping it here so that the reader doesn't miss it... but would at least add a comment like

`# this would generally be together with other imports at the top of the file`

2023-02-03 09:57 UTC, mjsambol approved these changes

2023-02-03 09:58 UTC, merged